### PR TITLE
feat: Add Access config

### PR DESCRIPTION
**Pull request by shinji62**
Adding Access config , IPV6 :
 Access configurations, i.e. IPs via which the VM instance can be accessed via the Internet.

### CODE REVIEW

**Review by apeabody — CHANGES_REQUESTED** [review]
Thanks for the contribution @shinji62!

Can you please address the lint findings:

```
Checking for documentation generation
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=autogen' '--exclude=*.tfvars' '--exclude=*metadata.yaml' /workspace/modules/tfc-agent-mig-vm/README.md /tmp/tmp.4sCu3DrVWY/generate_docs/workspace/modules/tfc-agent-mig-vm/README.md
26a27
> | access\_config | Access configurations, i.e. IPs via which the VM instance can be accessed via the Internet. | <pre>list(object({<br>    nat_ip       = string<br>    network_tier = string<br>  }))</pre> | `[]` | no |
30a32
> | ipv6\_access\_config | IPv6 access configurations. Currently a max of 1 IPv6 access configuration is supported. If not specified, the instance will have no external IPv6 Internet access. | <pre>list(object({<br>    network_tier = string<br>  }))</pre> | `[]` | no |
Error: Documentation generation has not been run, please run the
'make docker_generate_docs' command and commit the above changes.
Checking for trailing whitespace
Checking for missing newline at end of file
Error: No newline at end of file ./modules/tfc-agent-mig-vm/variables.tf
Running shellcheck
Checking file headers
Running flake8
/usr/local/bin/task_helper_functions.sh: line [30](https://github.com/GoogleCloudPlatform/terraform-google-tf-cloud-agents/actions/runs/10726190556/job/29745695898?pr=42#step:5:31): DELETE_AT_EXIT: readonly variable
Checking for tflint
Working in ./examples/oidc-simple using /root/tflint/.tflint.example.hcl...
tflint passed ./examples/oidc-simple 
Working in ./examples/tfc-agent-gke-custom using /root/tflint/.tflint.example.hcl...
tflint passed ./examples/tfc-agent-gke-custom 
Working in ./examples/tfc-agent-gke-simple using /root/tflint/.tflint.example.hcl...
tflint passed ./examples/tfc-agent-gke-simple 
Working in ./examples/tfc-agent-mig-container-vm-simple using /root/tflint/.tflint.example.hcl...
tflint passed ./examples/tfc-agent-mig-container-vm-simple 
Working in ./examples/tfc-agent-mig-vm-packer using /root/tflint/.tflint.example.hcl...
tflint passed ./examples/tfc-agent-mig-vm-packer 
Working in ./examples/tfc-agent-mig-vm-simple using /root/tflint/.tflint.example.hcl...
tflint passed ./examples/tfc-agent-mig-vm-simple 
Working in ./modules/tfc-agent-gke using /root/tflint/.tflint.module.hcl...
tflint passed ./modules/tfc-agent-gke 
Working in ./modules/tfc-agent-mig-container-vm using /root/tflint/.tflint.module.hcl...
tflint passed ./modules/tfc-agent-mig-container-vm 
Working in ./modules/tfc-agent-mig-vm using /root/tflint/.tflint.module.hcl...
tflint passed ./modules/tfc-agent-mig-vm 
Working in ./modules/tfc-oidc using /root/tflint/.tflint.module.hcl...
tflint passed ./modules/tfc-oidc 
Skipping ./test/setup
Running terraform fmt
modules/tfc-agent-mig-vm/main.tf
--- old/modules/tfc-agent-mig-vm/main.tf
+++ new/modules/tfc-agent-mig-vm/main.tf
@@ -168,12 +168,12 @@
  *****************************************/
 
 module "mig" {
-  source             = "terraform-google-modules/vm/google//modules/mig"
-  version            = "~> 11.0"
-  project_id         = var.project_id
-  region             = var.region
-  hostname           = local.instance_name
-  instance_template  = module.mig_template.self_link
+  source            = "terraform-google-modules/vm/google//modules/mig"
+  version           = "~> 11.0"
+  project_id        = var.project_id
+  region            = var.region
+  hostname          = local.instance_name
+  instance_template = module.mig_template.self_link
 
   /* autoscaler */
   autoscaling_enabled = true
Error: terraform fmt failed with exit code 3
Check the output for diffs and correct using terraform fmt <dir>
ENABLE_BPMETADATA not set to 1. Skipping metadata validation.
Error: The following tests have failed: check_documentation check_whitespace check_terraform
```

**Comment by shinji62** [comment]
@apeabody I addeed the change you wanted

**Comment by apeabody** [comment]
Looks like the CI TEST is seeing a permadiff:

```
TestTfcAgentGkeSimple 2024-09-11T03:51:17Z command.go:185: Terraform will perform the following actions:
TestTfcAgentGkeSimple 2024-09-11T03:51:17Z command.go:185: 
TestTfcAgentGkeSimple 2024-09-11T03:51:17Z command.go:185:   # module.tfc_agent_gke.module.tfc_agent_cluster.google_container_node_pool.pools["tfc-agent-pool"] will be updated in-place
TestTfcAgentGkeSimple 2024-09-11T03:51:17Z command.go:185:   ~ resource "google_container_node_pool" "pools" {
TestTfcAgentGkeSimple 2024-09-11T03:51:17Z command.go:185:         id                          = "projects/ci-tf-cloud-agents-a5c7/locations/us-central1-a/clusters/tfc-agent-k8s-dey7/nodePools/tfc-agent-pool"
TestTfcAgentGkeSimple 2024-09-11T03:51:17Z command.go:185:         name                        = "tfc-agent-pool"
TestTfcAgentGkeSimple 2024-09-11T03:51:17Z command.go:185:         # (11 unchanged attributes hidden)
TestTfcAgentGkeSimple 2024-09-11T03:51:17Z command.go:185: 
TestTfcAgentGkeSimple 2024-09-11T03:51:17Z command.go:185:       ~ node_config {
TestTfcAgentGkeSimple 2024-09-11T03:51:17Z command.go:185:             tags                        = [
TestTfcAgentGkeSimple 2024-09-11T03:51:17Z command.go:185:                 "gke-tfc-agent-k8s-dey7",
TestTfcAgentGkeSimple 2024-09-11T03:51:17Z command.go:185:                 "gke-tfc-agent-k8s-dey7-tfc-agent-pool",
TestTfcAgentGkeSimple 2024-09-11T03:51:17Z command.go:185:             ]
TestTfcAgentGkeSimple 2024-09-11T03:51:17Z command.go:185:             # (20 unchanged attributes hidden)
TestTfcAgentGkeSimple 2024-09-11T03:51:17Z command.go:185: 
TestTfcAgentGkeSimple 2024-09-11T03:51:17Z command.go:185:           - kubelet_config {
TestTfcAgentGkeSimple 2024-09-11T03:51:17Z command.go:185:               - cpu_cfs_quota                          = false -> null
TestTfcAgentGkeSimple 2024-09-11T03:51:17Z command.go:185:               - insecure_kubelet_readonly_port_enabled = "FALSE" -> null
TestTfcAgentGkeSimple 2024-09-11T03:51:17Z command.go:185:               - pod_pids_limit                         = 0 -> null
TestTfcAgentGkeSimple 2024-09-11T03:51:17Z command.go:185:                 # (2 unchanged attributes hidden)
TestTfcAgentGkeSimple 2024-09-11T03:51:17Z command.go:185:             }
TestTfcAgentGkeSimple 2024-09-11T03:51:17Z command.go:185: 
TestTfcAgentGkeSimple 2024-09-11T03:51:17Z command.go:185:             # (2 unchanged blocks hidden)
TestTfcAgentGkeSimple 2024-09-11T03:51:17Z command.go:185:         }
TestTfcAgentGkeSimple 2024-09-11T03:51:17Z command.go:185: 
TestTfcAgentGkeSimple 2024-09-11T03:51:17Z command.go:185:         # (5 unchanged blocks hidden)
TestTfcAgentGkeSimple 2024-09-11T03:51:17Z command.go:185:     }
TestTfcAgentGkeSimple 2024-09-11T03:51:17Z command.go:185: 
TestTfcAgentGkeSimple 2024-09-11T03:51:17Z command.go:185: Plan: 0 to add, 1 to change, 0 to destroy.
TestTfcAgentGkeSimple 2024-09-11T03:51:17Z command.go:185: 
TestTfcAgentGkeSimple 2024-09-11T03:51:17Z command.go:185: ─────────────────────────────────────────────────────────────────────────────
TestTfcAgentGkeSimple 2024-09-11T03:51:17Z command.go:185: 
TestTfcAgentGkeSimple 2024-09-11T03:51:17Z command.go:185: Note: You didn't use the -out option to save this plan, so Terraform can't
TestTfcAgentGkeSimple 2024-09-11T03:51:17Z command.go:185: guarantee to take exactly these actions if you run "terraform apply" now.
    terraform.go:537: 
        	Error Trace:	/builder/home/go/pkg/mod/github.com/!google!cloud!platform/cloud-foundation-toolkit/infra/blueprint-test@v0.16.1/pkg/tft/terraform.go:537
        	            				/workspace/test/integration/tfc-agent-gke-simple/tfc_agent_gke_simple_test.go:33
        	            				/builder/home/go/pkg/mod/github.com/!google!cloud!platform/cloud-foundation-toolkit/infra/blueprint-test@v0.16.1/pkg/tft/terraform.go:638
        	            				/builder/home/go/pkg/mod/github.com/!google!cloud!platform/cloud-foundation-toolkit/infra/blueprint-test@v0.16.1/pkg/tft/terraform.go:670
        	            				/builder/home/go/pkg/mod/github.com/!google!cloud!platform/cloud-foundation-toolkit/infra/blueprint-test@v0.16.1/pkg/utils/stages.go:31
        	            				/builder/home/go/pkg/mod/github.com/!google!cloud!platform/cloud-foundation-toolkit/infra/blueprint-test@v0.16.1/pkg/tft/terraform.go:670
        	Error:      	Should not be: 2
        	Test:       	TestTfcAgentGkeSimple
        	Messages:   	plan after apply should have no diff
```

**Comment by apeabody** [comment]
> @apeabody I did not change or touch this part, my guess would be that a different google provider version is use, maybe because of the bump of some Google module in my change.
> 
> But I don't think I can fix that myself.

Thanks @shinji62! - Very likely. I'll review this PR once the repo CI is updated.

**Comment by shinji62** [comment]
@apeabody Please let me know when you fix / find the issue :)

**Pull request closed without merging**
