### PR TITLE
feat: adding tests for the major submodules

### PR DESCRIPTION
**Pull request by gautambaghel**
FYI: This won't work without a Terraform cloud org name and a token

### CODE REVIEW

**Comment by g-awmalik** [comment]
@gautambaghel - take a look at these errors from the int test run: https://gist.github.com/g-awmalik/813e6b8a277dd8f7f9d84dec4230e6dc

**Comment by g-awmalik** [comment]
> @gautambaghel - take a look at these errors from the int test run: https://gist.github.com/g-awmalik/813e6b8a277dd8f7f9d84dec4230e6dc
> 
> It seems like you're not setting the TFC org name & the image name in the examples.

There are a couple of ways we can do this:
- you can create an output for the TFE org id and the image name [here](https://github.com/GoogleCloudPlatform/terraform-google-tf-cloud-agents/blob/main/test/setup/outputs.tf). These outputs are exported as env vars and are available to the examples. This is also how the [gcp project id](https://github.com/GoogleCloudPlatform/terraform-google-tf-cloud-agents/blob/main/examples/oidc-simple/variables.tf#L17) variable is set.
- Or you can set them directly in the example (non recommended since you'll end up setting the same ID multiple times across multiple exampled.

**Comment by gautambaghel** [comment]
@g-awmalik - This is expected, we need to pass the TFC token and TFC org name somehow...

The custom image however needs to be resolved, is there a way to create the image via the Cloudbuild pipeline? It's taken from the GH pipeline repo here -> https://github.com/terraform-google-modules/terraform-google-github-actions-runners/tree/master/examples/gh-runner-mig-native-packer

I need to know from Bharath how he tests these...

**Comment by gautambaghel** [comment]
@g-awmalik - We'll do the first approach you recommended, it seems doable but it still won't work if the TFC login token is not present on the machine (because the TFE provider needs that)

- you can create an output for the TFE org id and the image name [here](https://github.com/GoogleCloudPlatform/terraform-google-tf-cloud-agents/blob/main/test/setup/outputs.tf). These outputs are exported as env vars and are available to the examples. This is also how the [gcp project id](https://github.com/GoogleCloudPlatform/terraform-google-tf-cloud-agents/blob/main/examples/oidc-simple/variables.tf#L17) variable is set.

**Comment by gautambaghel** [comment]
These tests should run perfectly fine with a free Terraform Cloud account so if Google wants to create one and have complete ownership of it for security purposes I'm fine with it.

**Comment by g-awmalik** [comment]
> @g-awmalik - This is expected, we need to pass the TFC token and TFC org name somehow...
> 
> The custom image however needs to be resolved, is there a way to create the image via the Cloudbuild pipeline? It's taken from the GH pipeline repo here -> https://github.com/terraform-google-modules/terraform-google-github-actions-runners/tree/master/examples/gh-runner-mig-native-packer
> 
> I need to know from Bharath how he tests these...

I didn't realize the TFC token was part of this PR. For that we can use [secrets with cloud build](https://cloud.google.com/build/docs/securing-builds/use-secrets). Basically, you can set up the token and I'll put that in Secrets Manager in our CI/CD GCP that only the CI/CD service account will have access to. You'll just need to get it as an env var in the go test. 

However, TFC org name and image can still be set up as outputs since there's nothing sensitive there unless I'm mistaken. Let me know.

**Comment by g-awmalik** [comment]
> @g-awmalik - This is expected, we need to pass the TFC token and TFC org name somehow...
> 
> The custom image however needs to be resolved, is there a way to create the image via the Cloudbuild pipeline? It's taken from the GH pipeline repo here -> https://github.com/terraform-google-modules/terraform-google-github-actions-runners/tree/master/examples/gh-runner-mig-native-packer
> 
> I need to know from Bharath how he tests these...

Take a look at [building images with cloud build](https://cloud.google.com/build/docs/building/build-containers#use-buildconfig). Basically, you'll need to add after `prepare` where you can build the image and then set the name as an env var with a `TF_VAR_` prefix for the examples to pick it up.

**Comment by gautambaghel** [comment]
@g-awmalik - Added the fixes in the new commit, two things that need to be done before the tests work

* Put the TFC token and put that in Secrets Manager in the CI/CD
* The Cloud build pipeline service account that runs the integration tests needs to have Compute Instance Admin (v1) & Service Account User roles for the images to be created

Thanks!

**Comment by g-awmalik** [comment]
@gautambaghel - the secret should be available in cloud build as an env var as soon as https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/pull/1782 is applied.

**Comment by gautambaghel** [comment]
I think it's merged can you do a /gcbrun please? thx!

**Review by g-awmalik — APPROVED** [review]

**Pull request merged**
